# Riftbar Configuration

# Module positions (MUST be at root level, BEFORE any [sections])
modules_left = ["box/left_side"]
modules_center = ["hyprland/workspaces"]
modules_right = ["box/right_side", "custom/mako"]
# modules_right = ["revealer/quicksettings", "box/right_side"]


[bar]
height = 30
position = "top"  # top, bottom
layer = "top"     # background, bottom, top, overlay
spacing = 10

# Network module configuration
[network]
format = "{icon}"
format_disconnected = "󰖪 Disconnected"
format_ethernet = "󰈀 {ifname}"
interval = 5
# interface = "wlan0"  # Optional: specify interface
tooltip = true

# Available format placeholders for network:
# {icon} - Dynamic icon based on signal strength
# {essid} - WiFi network name
# {signalStrength} - Signal strength (0-100)
# {signalStrengthApp} - Signal strength with % symbol
# {ifname} - Interface name
# {ipaddr} - IP address

# Audio module configuration
[audio]
format = "{icon}"
format_muted = "{icon}"
interval = 100  # milliseconds
tooltip = true
# Custom actions (leave empty for default behavior)
on_click = ""  # Default: toggle mute
on_scroll_up = ""  # Default: increase volume by scroll_step
on_scroll_down = ""  # Default: decrease volume by scroll_step
scroll_step = 5  # Volume change step (percentage)

# Available format placeholders for audio:
# {icon} - Dynamic icon based on volume level (,, , )
# {volume} - Volume percentage (0-100)

# MPRIS (Media Player) configuration
[mpris]
format = "{icon} {status}"
format_playing = "{icon} {status}"
format_paused = "{icon} {status}"
format_stopped = "{icon} Stopped"
interval = 100  # milliseconds
tooltip = true
tooltip_format = "{artist}\n{album}\n{title}"

# Available format placeholders for mpris:
# {icon} - Dynamic icon based on playback state (,, )
# {artist} - Artist name
# {title} - Song title
# {album} - Album name
# {status} - Playback status (Playing, Paused, Stopped)

# Battery configuration
[battery]
format = "{icon}"
format_charging = "󰠠"
format_full = "{icon}"
interval = 30
# battery = "BAT0"  # Optional: specify battery (default: auto-detect)
tooltip = true

# Available format placeholders for battery:
# {icon} - Dynamic icon based on capacity and status
# {capacity} - Battery percentage
# {status} - Battery status (Charging, Discharging, Full, etc.)
# {time} - Time remaining/until full

# Clock module configuration
[clock]
format = " %H:%M"
interval = 1  # seconds
tooltip = true
tooltip_format = "%A, %B %d, %Y"
on_click = ""  # Optional: command to run on click

# Available format placeholders (uses date command format):
# %H - Hour (00-23)
# %M - Minute (00-59)
# %S - Second (00-59)
# %A - Full weekday name
# %a - Abbreviated weekday name
# %B - Full month name
# %b - Abbreviated month name
# %d - Day of month (01-31)
# %Y - Year with century

[boxes.quickcenter]
modules = ["network", "audio", "battery"]
action = "bash ~/.config/hypr/scripts/actioncenter.sh &  ewwii close calendar"
# orientation = "horizontal"  # horizontal or vertical (default: horizontal)

[boxes.left_side]
modules = ["custom/search", "custom/settings", "custom/arch","mpris"]

[boxes.right_side]
modules = ["box/quickcenter", "clock"]

# Revealer that shows on hover
[revealers.quicksettings]
modules = ["network", "audio", "battery"]
spacing = 5
trigger = "󰣇"
transition = "slide_left"
transition_duration = 200
reveal_on_hover = true

# Custom Notification Module
[custom_modules.mako]
action = "bash ~/.config/mako/scripts/rofi.sh"
exec = "echo '󰂚'"
interval = 999999
format = "{}"

# Custom Module 
[custom_modules.search]
action = ""
exec = "echo ' '"
interval = 999999
format = "{}"

# Custom Module 
[custom_modules.settings]
action = ""
exec = "echo ' '"
interval = 999999
format = "{}"

# Custom Module 
[custom_modules.arch]
action = ""
exec = "echo ''"
interval = 999999
format = "{}"
